name: Build and test
on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  build:
    uses: duckdb/extension-ci-tools/.github/workflows/_extension_distribution.yml@main
    with:
      extension_name: overture
      duckdb_version: v1.5.1
      ci_tools_version: main
